#!/usr/bin/bash
# Script requires windows event messages debug log generated by SELD deidentification pipeline formated as:
# eventid: message content
# Shows total records not identifed for deidentification, (based on event ID)
# Summary view groups records by event ID and displays top 15 Windows events not processed by pipeline
#
#
# 2023-04-03  POC validation, requires path and filename as parameter

if [ $# -eq 0 ]
    then
      echo "usage: ./winevt_unprocessedmessages.sh seld_winmsg_evtid-reident-assessment.log "
    exit 1
fi

winevtmsgreviewfile=$1

# Print total log records, unique and top contributors
echo " "
echo "Total records for : "$winevtmsgreviewfile
totalrecords=$(cat $winevtmsgreviewfile | wc -l | awk '{print $1}')
echo $totalrecords
echo "Number of unique event IDs: "
uniquerecords=$(cat $winevtmsgreviewfile | awk -F':' '{print $1}' | sort -n | uniq -c | sort -nr | wc -l | awk '{print $1}')
echo $uniquerecords
echo "Most frequent Windows event IDs with no message field deidentification:"
cat $winevtmsgreviewfile | awk -F':' '{print $1}' | sort -n | uniq -c | sort -nr | head -15 